### ISSUE TITLE
Problem importing package on Linux

### ISSUE THREAD

**Issue by ludoroo** [crispitagorico/SignatureKernel#2]
Hello, thanks for making your code available. I've tried installing and using your package on Linux and I get the following error:
```
>>> import sigkernel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/****/miniconda3/envs/stein/lib/python3.9/site-packages/sigkernel/__init__.py", line 3, in <module>
    from .sigkernel import *
  File "/home/***/miniconda3/envs/stein/lib/python3.9/site-packages/sigkernel/sigkernel.py", line 6, in <module>
    from cython_backend import sig_kernel_batch_varpar, sig_kernel_derivative_batch_varpar, sig_kernel_Gram_varpar
ImportError: cannot import name 'sig_kernel_derivative_batch_varpar' from 'cython_backend' (/home/****/miniconda3/envs/stein/lib/python3.9/site-packages/cython_backend.cpython-39-x86_64-linux-gnu.so)
```

Maybe the Linux cpython file needs to be recompiled?

**Comment by crispitagorico** [comment]
Hi and sorry for this massive delay in answering your question. Can you please try uninstalling sigkernel and installing it back using the pip-install command at the top of the README file?
